export interface VipReaction {
    id: string;
    name: string;
    src: string;
    tags: readonly string[];
}

/**
 * Shared paid Catpuss artwork for stickers, inline emoji and reactions; IDs remain stable in saved messages.
 * Art is generated by output/catpuss-stickers/build.cjs; keep IDs in sync with the backend VipCharacterCatalog.
 */
export const VIP_REACTIONS: readonly VipReaction[] = [
    {id: 'catpuss-cheer', name: 'Cheering Catpuss', tags: ['yay', 'hooray', 'celebrate', 'happy', 'excited']},
    {id: 'catpuss-typing', name: 'Typing Catpuss', tags: ['laptop', 'typing', 'working', 'busy', 'computer']},
    {id: 'catpuss-love', name: 'Heart Hug Catpuss', tags: ['love', 'heart', 'hug', 'cute', 'thanks']},
    {id: 'catpuss-heart-eyes', name: 'Heart Eyes Catpuss', tags: ['love', 'crush', 'adore', 'heart eyes']},
    {id: 'catpuss-laugh', name: 'Laughing Catpuss', tags: ['lol', 'lmao', 'funny', 'joy', 'haha']},
    {id: 'catpuss-cry', name: 'Crying Catpuss', tags: ['sob', 'tears', 'sad', 'feels']},
    {id: 'catpuss-sad', name: 'Sad Catpuss', tags: ['sad', 'down', 'gloomy', 'feels', 'rain']},
    {id: 'catpuss-angry', name: 'Angry Catpuss', tags: ['mad', 'grumpy', 'annoyed', 'hmph']},
    {id: 'catpuss-rage', name: 'Rage Catpuss', tags: ['furious', 'screaming', 'rage', 'fire']},
    {id: 'catpuss-shock', name: 'Shocked Catpuss', tags: ['surprised', 'omg', 'wow', 'gasp']},
    {id: 'catpuss-think', name: 'Thinking Catpuss', tags: ['hmm', 'thinking', 'wonder', 'pondering']},
    {id: 'catpuss-smart', name: 'Big Brain Catpuss', tags: ['smart', 'genius', 'idea', 'nerd', 'glasses']},
    {id: 'catpuss-smug', name: 'Smug Catpuss', tags: ['smirk', 'knowing', 'sly']},
    {id: 'catpuss-cool', name: 'Cool Catpuss', tags: ['sunglasses', 'chill', 'swag', 'confident']},
    {id: 'catpuss-strong', name: 'Strong Catpuss', tags: ['muscles', 'gym', 'strong', 'workout', 'lift']},
    {id: 'catpuss-shy', name: 'Shy Catpuss', tags: ['blush', 'awkward', 'embarrassed', 'nervous']},
    {id: 'catpuss-sleepy', name: 'Sleepy Catpuss', tags: ['tired', 'sleep', 'zzz', 'night', 'bored']},
    {id: 'catpuss-party', name: 'Party Catpuss', tags: ['party', 'birthday', 'confetti', 'celebrate']},
    {id: 'catpuss-confused', name: 'Confused Catpuss', tags: ['huh', 'what', 'question', 'dizzy']},
    {id: 'catpuss-blank', name: 'Blank Stare Catpuss', tags: ['neutral', 'meh', 'blank', 'unimpressed']},
    {id: 'catpuss-silly', name: 'Silly Catpuss', tags: ['wink', 'tongue', 'playful', 'goofy']},
    {id: 'catpuss-thumbs-up', name: 'Thumbs Up Catpuss', tags: ['yes', 'ok', 'agree', 'like', 'approve']},
    {id: 'catpuss-wave', name: 'Waving Catpuss', tags: ['hi', 'hello', 'bye', 'wave']},
    {id: 'catpuss-please', name: 'Pleading Catpuss', tags: ['please', 'beg', 'puppy eyes', 'pretty please']},
    {id: 'catpuss-peek', name: 'Peeking Catpuss', tags: ['peek', 'lurk', 'watching', 'observer', 'quiet']},
].map(reaction => ({...reaction, src: `/stickers/vip/${reaction.id}.png`}));

const reactionPrefix = 'allchat:';
const reactionsByToken = new Map(VIP_REACTIONS.map(reaction => [toCustomReactionToken(reaction.id), reaction]));
const stickersById = new Map(VIP_REACTIONS.map(sticker => [sticker.id, sticker]));

/** Sticker messages use a short catalog ID, never a URL or a reaction token. */
export function getSticker(id?: string | null): VipReaction | undefined {
    return id ? stickersById.get(id) : undefined;
}

export function getStickerLabel(id?: string | null): string {
    const sticker = getSticker(id);
    return sticker ? `${sticker.name} sticker` : 'Unavailable sticker';
}

export function toCustomReactionToken(id: string): string {
    return `${reactionPrefix}${id}`;
}

/** Recognize even unavailable reserved tokens so they never render as URLs or raw IDs. */
export function isCustomReactionToken(emoji?: string | null): boolean {
    return Boolean(emoji?.startsWith(reactionPrefix));
}

/** Only an exact allowlisted identity may resolve an image. */
export function getCustomReaction(emoji?: string | null): VipReaction | undefined {
    return emoji ? reactionsByToken.get(emoji) : undefined;
}

export function getReactionLabel(emoji: string, emojiId?: string): string {
    const reaction = getCustomReaction(emoji);
    if (reaction) return reaction.name;
    if (isCustomReactionToken(emoji) || isCustomReactionToken(emojiId)) return 'Unavailable reaction';
    return emojiId?.replaceAll('_', ' ') || emoji;
}
